### SUPERVISED LEARNING
```Supervised learning is a class of ML algorithms that takes in a series of vectors and their corresponding output as input, and produces an inferred function that can be used to map new example.```


```_Supervised learning can be classified into two types: REGRESSION & CLASSIFICATION__```

``` A classification problem has a discrete set of values as the target variable( for instance , a like & dislike)  whereas```
```A regression problem has a continous value as its target( for instance , an average rating between one and five)```

#### KNN

``` It's the simplest ML algorithms```
```incase of classification, it assign a class to a particular data points by a majority vote of k nearest neighbours, in other words,the data points is assigned the class that is the most common among its k-nearest neighbours```
``in regression computes the average values for the largest variables based on K-nearest neighbours```


```KNN is non-parametric & lazy in nature. This means that KNN does not make any underlying assumption about the distribution of the data.```
```In other words , the model is determined by the data & the latter means that KNN undergoes virtually no training. It computes the K-nearest  neighbours of a particular points in prediction phase.```
``This mean that the K-NN model needs to have access to the training data at all times and cannot discard it during prediction like its sister algorithms.```

In [2]:
# import libraries
import numpy as np
import pandas as pd

# url & names
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

#Load the Iris dataset into pandas Dataframe
iris = pd.read_csv(url,  names=names)

# Display iris head
iris.head()


sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [36]:
# Pre-processing

# split our iris into attributes & labels
X = iris.iloc[:, :-1]
y = iris.iloc[:, 4]

In [39]:
# split to test & train data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y , test_size=0.20) #80% train 20% test

In [42]:
# feature scaling so that all of them are  uniformly evaluated
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [43]:
# training & predicting
from sklearn.neighbors import KNeighborsClassifier

# classify
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [46]:
# predict on our test data
y_predict = classifier.predict(x_test)

In [51]:
# Evaluating the algorithms
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

[[ 5  0  0]
 [ 0 14  1]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         5
Iris-versicolor       1.00      0.93      0.97        15
 Iris-virginica       0.91      1.00      0.95        10

      micro avg       0.97      0.97      0.97        30
      macro avg       0.97      0.98      0.97        30
   weighted avg       0.97      0.97      0.97        30



#### Support Vector machine

```-classification algorithms that takes in an n-dimensional dataset as input and constructs an (n-1) dimensional hyperplane in such a way that there is maximum separation of classess```

#### ENSEMBLING 
``` THE MAIN IDEA BEHIND ENSEMBLING IS THAT THE PREDICTIVE POWER OF MULTIPLE ALGORITHMS IN MUCH GREATER THAN A SINGLE ALGORITHM. --Decision trees are the most common base of algorithms used when building ensembling model```

###### Bagging & Random Forests. (short for bootstrap aggregating)

In [54]:
# Like most other ensembling methods, it averages over a large number of base prediction
# of base classification & averages their results in deliver its final prediction

##### Boosting

In [55]:
# Like random forest, boosting models build a baseline model using a subset of samples and
# features . However, while building the next learners, the boosting model tries to rectify
# the mistakes that the previous learners made.

In [58]:
# Divide the dataset into the features dataframe & athe target class series
X, y = iris.drop('class', axis=1), iris['class']

# split the data into training & test datasets
# we will train on 75% of the data  and assess our perfomance on 25% of the data

# import the splitting fucntion
from sklearn.model_selection import train_test_split

X_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=0)

# import the Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier

# Apply Gradient Boosting to the training data
gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)

# compute the accuracy on the test set
gbc.score(x_test, y_test)

0.9736842105263158

In [59]:
# Display a bar plot of feature importance
import seaborn as sns

sns.barplot(x=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], y=feature_importance_instance_)

NameError: name 'feature_importance_instance_' is not defined